name: mellotron
channels:
  - defaults
dependencies:
  - conda
  - pip
  - matplotlib#==2.1.0
  - inflect#==0.2.5
  - librosa#>0.6.0
  - numpy
  - scipy#>1.0.0
  - Unidecode#==1.0.22
  - pillow
  - music21
  - python=3.8
  - pytorch
  - pysoundfile
  - pandas
  - tensorflow<2.0
  - jupyter
  - jupyterlab
  - pip:
    - environment-kernels
    - tensorboardX==1.1
    - nltk==3.4.5
    - jamo==0.4.1
